### ISSUE TITLE
Incorrect pitch for tips up sub-block pin grid

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#1284] opened 2023-05-30 20:25 UTC
In the same vein of #1278, the pin pitch seems to be off. The following grid definitions
```yaml
  pins:
    lattice pitch:
      x: 1.2
      y: 1.2
    geom: hex_corners_up
    lattice map: |
      - - O F F
       - F F F F
        F F F F F
         F F F F
          F F F
    # geom: hex
    # lattice map: |
    #   - F
    #    F F
    #   F F F
    #    F F
    #   F F F
    #    F F
    #   F F F
    #    F F
    #     F 
```
produce two different pitches. For the normal "flats up" hexagon, the pitch is correct: `b.spatialGrid.pitch=1.2`. But for the "tips up" grid, the pitch is off: `b.spatialGrid.pitch=1.0392304845413265` using
```python
import armi
armi.configure()
o = armi.init(fName="sample.yaml")
b = o.r.core[0][0]
g = b.spatialGrid
print(f"{b.spatialGrid.pitch=}")
```

My current workaround is to look at the `_unitSteps` attribute, which feels not ideal (using private attribute) 
```python
>>> b.spatialGrid._unitSteps
array([[ 0.6       , -0.6       ,  0.        ],
       [ 1.03923048,  1.03923048,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])
>>> realPitch = b.spatialGrid._unitSteps[0,0] * 2
```
If I understand these right, the `_unitSteps[0, 0]` is the change in x for changing ring. So each new ring nets us a full new x-site, since they're all neighbors.

**Comment by drewj-usnctech** [comment] 2023-05-30 20:28
In digging around to find out if this is a bug or not, I was reminded of https://github.com/terrapower/armi/issues/252 where the ["undocumented"](https://github.com/terrapower/armi/issues/252#issuecomment-782252527) way to define a pitch for a hexagonal sub-assembly lattice is to use the x/y pitches
```yaml
lattice pitch:
  x: 1.2
```
which still feels weird. Would it be worth making a separate issue for supporting a scalar for "regular" hex or cartesian grids?
```yaml
lattice pitch: 1.2
```
feels a lot easier to explain to new users

**Comment by keckler** [comment] 2023-05-30 20:48
Thank you for posting this. I think that this is clearly a bug, and needs to be fixed. 

I do not know of any reason that such a scalar `lattice pitch` could not be supported, and I would like to see it implemented.

**Comment by drewj-usnctech** [comment] 2023-07-24 15:55
Bump on this nice to have feature

**Comment by john-science** [comment] 2023-08-23 16:55
Order of Operations:

1. PR 1373 goes through.
2. Modify `HexGrid` to be two subclasses: Tips Up or Flats Up (or add an attribute in the class, or something)
3. Modify these method to solve this ticket.

**Comment by john-science** [comment] 2024-02-27 17:17
I think there may be a little confusion here.

The distances defined by `x` and `y` here are the "flat-to-flat" distance, whether the `HexGrid` is flat-to-flat or "corners up":

https://github.com/terrapower/armi/blob/6163e942abe873129533b84a6f2efa632f260b47/armi/reactor/grids/hexagonal.py#L110-L111

This exactly explains your numerical problem above:

```
1.0392304845413265 = math.sqrt(3)/2 * 1.2
```

And that factor (`math.sqrt(3)/2`), is the ratio of the "flat-to-flat" diameter of a hexagon over the "corner-to-corner" diameter.

I think this is not a bug, but just a misunderstanding.  I would normally just close this ticket, but perhaps @drewj-usnctech could tell me where better to put this information so it would have been visible to him from the get-go? I don't want other people to run into the same problem, of course. And that docstring is apparently too hidden.

**Closed** 2024-03-19 21:43 UTC
Labels: bug
