### ISSUE TITLE
Request: Allow `UnshapedComponent`s to thermally-expand

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#591] opened 2022-03-08 21:47 UTC
Right now we have the `UnshapedComponent` which allows a user to just enter the volume/area fraction of a component without having to worry explicitly what shape the component is:
https://github.com/terrapower/armi/blob/6dcedacdea505a508cf85119b4eb22953a1763e0/armi/reactor/components/__init__.py#L116-L121

This is nice, but right now these components are not allowed to thermally-expand:
https://github.com/terrapower/armi/blob/6dcedacdea505a508cf85119b4eb22953a1763e0/armi/reactor/components/__init__.py#L150-L159

(Note that the method signature and docstring imply that thermal expansion is possible, but the actual implementation contradicts this)

It would be nice to allow such components to thermally-expand. Though we don't know specific parameters of the shape like radius, pitch, or side-length, we could still get the thermally-expanded area of the component just by using the thermal expansion coefficient directly. Since the areal thermal expansion is just twice the linear thermal expansion, and all material classes will have the linear expansion coefficient, it seems like we should have all that is needed to calculate the thermally-expanded area of `UnshapedComponents`.

This would allow for modeling thermal expansion effects in models when only the volume fractions are known (common in fast reactor benchmark specifications).

**Comment by john-science** [comment] 2022-03-08 22:59
> Note that the method signature and docstring imply that thermal expansion is possible

Where does it say that?

I see that it says "Compute the area with as-input dimensions instead of thermally-expanded".

Logically, it doesn't seem possible to thermally expand something you don't know the geometry of.  For instance: if you don't know the height, how are you supposed to know how much to expand the height?

If something doesn't have known dimensions, how would you expand those dimensions?

You know?

**Comment by keckler** [comment] 2022-03-08 23:46
> Where does it say that?

The method has an optional parameter `cold` that is said to allow you to compute the area with "as-input dimensions instead of thermally-expanded". But `cold` is never used. So it implies that you can either get the area for the cold or hot component, but that's not the case. It will always be cold.

**Comment by keckler** [comment] 2022-03-08 23:56
> Logically, it doesn't seem possible to thermally expand something you don't know the geometry of. For instance: if you don't know the height, how are you supposed to know how much to expand the height?

> If something doesn't have known dimensions, how would you expand those dimensions?

But we have the area. You can expand the area itself without knowing the dimensions that lead to that area.

https://courses.lumenlearning.com/boundless-physics/chapter/thermal-expansion/#:~:text=area%20thermal%20expansion%20coefficient

**Comment by john-science** [comment] 2022-03-09 00:13
> > Where does it say that?
> 
> The method has an optional parameter `cold` that is said to allow you to compute the area with "as-input dimensions instead of thermally-expanded". But `cold` is never used. So it implies that you can either get the area for the cold or hot component, but that's not the case. It will always be cold.

The parameter `cold` has to be included because this is a subclass of the same method on the `class Component`, which provides the `cold` parameter.  It is just an oddity of Python that all subclassed methods need to have the same signature.

**Comment by john-science** [comment] 2022-03-09 00:17
> But we have the area...

https://github.com/terrapower/armi/blob/6dcedacdea505a508cf85119b4eb22953a1763e0/armi/reactor/components/__init__.py#L116-L121

It is explicitly state the only purpose for this class is to let people "enter the area directly".  I guess I will have to ask around and see who is using this, and if it would ruin them if we changed the method to have automatic thermal expansion.

**Comment by keckler** [comment] 2022-03-09 00:24
I guess I do not personally read that as saying "This will not be thermally-expanded". I just read it as saying that the user doesn't need to know what specific shape it is.

As with all components, the user could always enter `Thot` and `Tinput` as equal in the case that they don't want the area to change. Both of those attributes are passed to the `__init__`, so there shouldn't be any problem with actually using them here.

The way I view it, this wouldn't be taking any functionality _away_ from the user, it would just put this component in line with all the others. But that's just my take.

**Comment by john-science** [comment] 2022-03-09 00:26
Yeah, it appears the usual use-case for `UnshapedComponent` is as a space-filler.  People are using it when... say 30% of an area is fuel, 40% is coolant and the left-over is _some_ material.

In that use case, the left-over material is given a defined area. And in that use case having that material thermally expand would ruin everything.

So, is there some use-case you have where you want something like `UnshapedComponent`, but it thermally expands?

**Comment by keckler** [comment] 2022-03-09 02:08
Yeah, my sort of use-case would be when I have known components that I don't care to model their actual shapes (or I don't know their actual shapes), but I still want to capture what happens when temperature changes. 

For instance, it is pretty common for people to provide a description of a fast reactor in terms of just volume fractions. They don't say exactly what the shapes and dimensions are, they just say "we have 40% fuel, 30% steel, and 30% coolant". In that case, I know what the materials are for each of them, and I could, in theory, model the thermal expansion of those materials without knowing what the actual shapes are. This would allow me to model things like the reactivity response as temperature increases by just directly expanding the `UnshapedComponent`s.

Another similar case is when the geometry is just really complex and I don't want to explicitly represent the shapes. Like in an orifice block at the bottom of an assembly or the region where the pins connect to the inlet nozzle. There's no way that I could describe the actual geometry of those regions with the shapes in ARMI, but that doesn't mean I don't want to model the changing volume fractions as the components thermally-expand. 

Things like this are not possible right now, but would be if `UnshapedComponent` could be thermally-expanded.

**Comment by keckler** [comment] 2022-03-09 19:55
In effect, this capability would add into ARMI a modeling option with fidelity somewhere in between explicitly-defined components and the use of a fully-smeared custom material occupying the entire block.

**Comment by john-science** [comment] 2022-03-10 03:05
I'm not sure we can abandon `UnshapedComponent` right now. I know for your use-case it's inadaquate for your use case, but people are using it right now.

It sounds like what we need is `ExpandableUnshapedComponent(UnshapedComponent)`, which is a subclass where the only difference is the `getArea()` method.

I've been staring at this for a while trying to decide if `ExpandableUnshapedComponent` (patent pending) belongs in the repo proper, or if we should just put that in your code. On the one hand, it's not much code. On the other hand, if only one user ever wants it, it doesn't belong in the code base.

I'm torn.

**Comment by jakehader** [comment] 2022-03-10 06:36
Hi @john-science, I spoke with Chris on this and it seems that right now the behavior of the Unshaped component temperature inputs is not valid and maybe that is the point that is trying to be made here. As in, the density of materials assigned to an Unshaped component don't get modified because maybe there is nothing to do so. I suggested to Chris that he explore adding a failing unit test on the intended behavior we are looking for and then we can figure out if this treatment should be handled here (removing temperature inputs if they are not valid) or as you suggest making a different class all together. I like the idea of a new class to handle this. Also, without looking through the code I don't think people are using Unshaped components directly, but instead using Derived components for coolant. Maybe this is a subclass of an Unshaped component (again, I'd have to go look).

Either way, I like your suggestion of a new class type if that is the easiest and then making it super clear that a base Unshaped component will not thermally expand with a see also pointing to the class that does.

**Comment by keckler** [comment] 2022-03-10 15:49
Thanks @jakehader for chiming in.

@john-science , take a look at the following example which supports why I think that `UnshapedComponent`s should thermally-expand. If one creates an `UnshapedComponent`, mass of the component will not be preserved as the component changes temperature.

```
>>> import armi; armi.configure(); from armi.reactor.components import factory
>>> class _Parent:
            def getSymmetryFactor(self):
                return 1.0
            def getHeight(self):
                return 1.0
>>> a = factory(shape='unshapedcomponent', bcomps=[], kwargs={'area': 1, 'name': 'myComponent', 'material': 'HT9', 'Tinput': 25, 'Thot': 25})
>>> a.parent = _Parent()
>>> a.getArea()
1
>>> a.getMass()
8.860391313331757
>>> a = factory(shape='unshapedcomponent', bcomps=[], kwargs={'area': 1, 'name': 'myComponent', 'material': 'HT9', 'Tinput': 25, 'Thot': 500})
>>> a.parent = _Parent()
>>> a.getArea()
1
>>> a.getMass()
8.712731920200376
>>> 8.860391313331757 / 8.712731920200376
1.0169475423
>>> a.getThermalExpansionFactor() ** 2
1.011266686346159
```
In effect, ARMI thinks the mass of the component decreases as the temperature increases, because its material density decreases but the area stays the same.

**Comment by keckler** [comment] 2022-03-10 15:57
Also, just to clarify, I am not advocating that we get abandon the functionalities of `UnshapedComponent`. I think that people will still be able to get the behavior that you mention (i.e. a component that does not thermally-expand) if they just set `Thot = Tinput`. Adding thermal expansion will not remove that possibility.

**Comment by john-science** [comment] 2022-03-10 17:46
Your example above is worrisome.

In an effort to understand backwards compatibility, I went hunting for external projects that used `UnshapedComponent`s.  I couldn't find any. On the one hand, perhaps that's good news. We could just fix it without adding a new class. On the other hand, I would like to see who is really using this in the wild, to reduce the risk of breaking someone's toys, you know?

**Comment by keckler** [comment] 2022-03-10 18:13
Definitely I understand that. 

Please let me know how I can be helpful in getting this resolved. I think the path I would advocate for has been made clear by this point, but I am open to different solutions. I just think that _something_ is inconsistent with `UnshapedComponent`, and we need to make it right.

**Comment by john-science** [comment] 2022-03-10 21:12
From the docs on `UnshapedComponents`:

https://terrapower.github.io/armi/user/inputs/blueprints.html#making-blocks-with-unshaped-components

```Warning

When using this method avoid thermal expansion by setting TInput=THot, or your pitch component dimensions might change, thus changing your pitch.
```

I'd have to look through the density and thermal expansion calculations, but maybe we could Enforce that `TInput` and `THot` are always the same.

If that stops all changes in density and expansion it would enforce the rule we suggest here, and conserve mass.

**Comment by keckler** [comment] 2022-03-10 21:25
I do not believe that warning is referring to what we're talking about here. It is warning the user to make `Tinput=Thot` for the `Rectangle` component so that the assembly doesn't change pitch. Because that warning doesn't describe the error that would occur if `Tinput != Thot` in the `UnshapedComponent`s (i.e. you'd lose mass).

**Comment by jakehader** [comment] 2022-03-19 16:41
@keckler can this be closed now?

**Closed** 2022-03-19 17:02 UTC
Labels: feature request
