### ISSUE TITLE
Issues with `_swapFluxParam`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#566] opened 2022-02-08 17:30 UTC
When creating a fuel shuffling script, a user will typically use methods like `dischargeSwap`, `swapAssemblies`, and `swapCascade`, all of which make a call to [`_swapFluxParam`](https://github.com/terrapower/armi/blob/b94744fdf12f247828dd07bf99e251651b494a13/armi/physics/fuelCycle/fuelHandlers.py#L1418). Ostensibly the purpose of `_swapFluxParam` is to give blocks introduced into the core the info needed for weighting of cross-sections (or other similar needs) by supplying the incoming blocks with the flux, multi-group flux, and power of the out-going blocks. There are a couple issues I see with this method.

1. The in-coming and out-going assemblies are assumed to have the same number of blocks. If they don't, the swapping of information stops at the lesser of the number of blocks between the two assemblies. This means that power in the core may not be conserved when a new assembly is introduced. Obviously this is a fictional problem, but it can lead to issues with the `NeutronicsUniformMeshConverter._checkConversion` method's check on the power throughout the core. https://github.com/terrapower/armi/blob/a46fa86eaa00e74eb81398620d2cbcca4b5bac46/armi/reactor/converters/uniformMesh.py#L354-L358
2. Swapping the power between assemblies is potentially problematic for a number of reasons. If one ever wanted to look at the power of an assembly in the spent fuel pool, for instance, it could be arbitrarily wrong because when the assembly entered the SFP it was assigned the power from the assembly that it took the place of. 
3. When assemblies throughout the core are made up of blocks of widely varying heights, the flux swapping is probably a very poor approximation regardless of the two assemblies having the same number of blocks.

I think this method could be improved. At the very least, point (1) above is a bug that I personally need fixed.

One way that I could potentially foresee fixing points (1) and (3) is, instead of directly copying the flux/power between blocks of the same index, the flux from the out-going blocks could be approximated using a series expansion and the flux in the incoming blocks could be evaluated from that expansion. This would account for blocks being of vastly different heights and could also preserve power/flux during the swap.

Point (2) seems more problematic to me. I could also envision a scenario where we don't swap the powers at all, but instead we just fix the uniform mesh checks to adhere to physical reality. Then the power associated with each assembly would remain physical.

Any thoughts? There's probably a million ways to slice this.

**Comment by jakehader** [comment] 2022-02-08 23:08
I don't have any immediate insights but this sounds like a major bug that should be addressed. It sounds like there have been a lot of assumptions baked into the converters and other plugins / physics that may rely on this which is also not great

**Comment by keckler** [comment] 2022-02-08 23:34
I think there are a few different issues here that could potentially be split out. 

For instance, I am being blocked right now by Point (1). It would be very easy for me to change the way that is done to eliminate the bug, even if its not the final solution that we want to move towards. Probably the easiest thing would just to split the assembly-integrated power between the incoming blocks in the case that the number of blocks does not line up. Then power is conserved during the swap and the code no longer fails during the uniform mesh checking. 

The other problems are probably larger in scope, but of lower importance to me right now.

We definitely need another set of eyes on this, whenever @john-science or @ntouran can take a look.

**Comment by john-science** [comment] 2022-02-09 18:44
I'm looking at this now.

My guess is we need to linearly interpolate the power density in the blocks between the two assemblies. And then re-calculate the power in each block from the resulting density.

Hopefully, I can abuse/re-use the uniform-mesh-converter logic we have now.  But TBD.

**Comment by john-science** [comment] 2022-03-02 17:02
I believe my recent PR fixed not only (1) above, but also (3).  As my [new method](https://github.com/terrapower/armi/pull/577/files#diff-d0eee2bbf22ce1519f1403e71e6c2e60ea0dbe48bb6a63cc68369a1f1901d9f4R19) maps linearly along the vertical axis of the assembly.

Also, I think (2) above is by design in ARMI, and not likely to change any time soon.

If you want to open a discussion of (2) above, we can talk about how ARMI might be designed differently. Until then, I am closing this ticket.

**Closed by john-science** 2022-03-02 17:02 UTC
Labels: bug, complex

**Comment by keckler** [comment] 2022-03-03 03:45
Thanks for your effort on this, @john-science . I think this makes the approximations of `_swapFluxParam` much better.

Now that I am giving it some more thought, though, I am wondering what is even the point of the code making calls to `_checkConversion` during runtime. This seems like something that belongs in a unit test, not in a production run. 

Considering the false-issues that have spawned from `_checkConversion` taking place during runs (this ticket as well as #471), I'm wondering if it would make sense to just remove the call to `_checkConversion` from the uniform mesh generator? I don't really see a reason why it should be there, but maybe you do?

I personally don't think there is any physical basis for ARMI to require that the total power/flux between meshes used in different cycles stay the same.
