### ISSUE TITLE
Perform OS check at `import armi` time

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1694] opened 2024-04-24 17:45 UTC
Because we are trying to get internal ARMI applications working on a Linux system, we are beginning to add a lot of OS checks throughout ARMI.

We don't want to add this all over the place:
```python
if windows:
    this
elif linux:
    that
else:
    OS fail
```

Instead, the proposal is to perform this check at import time. 
```python
if windows:
    armi.OS = windows
elif linux:
    armi.OS = linux
else:
    OS fail
```

Then everywhere that has OS-dependence in the code base can handle things a little more simply:
```python
if windows:
    this
else:
    that
```

**Comment by john-science** [comment] 2024-04-24 17:47
I am going to close this, as it is a duplicate of another ticket: https://github.com/terrapower/armi/issues/1693

**Closed by john-science** 2024-04-24 17:47 UTC
Labels: enhancement, architecture
