### ISSUE TITLE
Global assembly numbering makes reactor objects not repeatable. 

### ISSUE THREAD

**Issue by alexhjames** [terrapower/armi#903] opened 2022-09-27 16:07 UTC
Currently, the assembly number is assigned to an assembly based on a global property on the assembly module.

https://github.com/terrapower/armi/blob/da952edc06b7cbe7374eb105be2134c64cab92cb/armi/reactor/assemblies.py#L36-L44

With this setup, this means that the assembly number in a given reactor depends on what other reactors you were just working with. This causes problems in some unit testing situations because the assembly number is not repeatable run to run because it depends on what you did in neighboring tests. The assembly number should be assigned by the reactor object as the reactor object knows how many assemblies are in the reactor. 

Alternatively, the assembly object should have a unique identifier that is stable from run to run. Currently assemNum is being used as that stable identifier because it is the only thing that is unique to an assembly and doesn't change with shuffling/etc.

**Comment by john-science** [comment] 2022-09-27 16:45
I have to agree, this "just use a global variable" approach to counting assemblies in a Reactor was definitely the easiest solution at the time of writing, but it is a constant supply of low-level annoyance now.

Issues with `global _assemNum`:

* It is _impossible_ to have two reactors in memory at the same time.
* Why is number of assemblies on each Assembly object, instead of on the Reactor object?
* The order the assemblies are created in, will mean the labels on the reactor are different.
  * This means the _order_ you create the Reactor assemblies matters, which is a hysteresis problem.
* This global number hides the truth, and makes changing it _hard_.

Complications with fixing this problem:

* This is a redesign that will have big side-effects.
* If the Reactor needs to have the true count of assemblies, will you need a Reactor object just to create an assembly?
* Can we have an `Reactor.addAssembly()` that goes through and does the count THEN?
* Probably, many downstream projects would have to be altered for this change.

I expect this to be a moderately sized task; a redesign with fingers in various directions. But I am strongly in favor of making the switch away from `global _assemNum`.

**Comment by john-science** [comment] 2022-09-27 16:45
@jakehader @keckler @ntouran Thoughts?

**Comment by keckler** [comment] 2022-09-27 19:59
I have personally had issues with the global `_assemNum` in the past, and I agree with Alex's comments on why it can be confusing/problematic.

To my understanding, if the reactor wants to know the number of assemblies, it can easily iterate over its grid (plus that of the SFP, if needed). And this is not expensive either.

So probably the real purpose in having a globally-unique number is to uniquely identify the assemblies. To this end, I have always thought that `_assemNum` was perhaps redundant because all ARMI objects already have a globally unique `serialNum` parameter:
https://github.com/terrapower/armi/blob/da952edc06b7cbe7374eb105be2134c64cab92cb/armi/reactor/parameters/parameterCollections.py#L47-L65

Regardless, the global `serialNum` parameter still doesn't solve @alexhjames 's problem, because the value is still stored on the module level, so your tests will still depend on whatever ARMI objects were created in previous tests.

One question is -- why do assemblies need to inherently have an assembly number? If it is not _in_ a reactor/core (or a reactor/core-like container), then I don't see any reason why the assembly would need to be uniquely identified. It will just exist in space, and unless you put it into a reactor, it will be cleared from memory once it goes out of scope, in which case you'll never need its assembly number anymore. 

So my thought is that the assembly number should only be assigned when it is put _into_ a reactor/core container, in which case the unique incrementer will be stored on the container itself.

This still wouldn't solve the niche problem of, "what if there are multiple reactors at the same time and you want to move assemblies between them?" I guess John says that this is not possible right now, but it seems like something I could imagine eventually being desirable, and in that case we'd have an issue.

**Comment by john-science** [comment] 2022-10-03 18:18
I will flush out some task requirements in a bit. But my current feeling is that a better design would be:

* a new `Assembly` has an empty/blank/null name
* an `Assembly` is not given a name until it is added to a `Reactor` using something like `Core.add()`
* during the life cycle of a `Reactor`, each `Assembly` should have a unique name
* the name/id for each `Assembly` should be reproducible, if the same run is done several times

**Comment by albeanth** [comment] 2022-10-03 18:23
@john-science That's a great list! I especially dig the last bullet. Just a quick thought on the second bullet. We'll likely want to consider adds to the SFP as well. An example of this is here https://github.com/terrapower/armi/blob/7be2ad9dd7fce738f2c5f9a85093a7c841533e6e/armi/reactor/tests/test_reactors.py#L188-L191

**Comment by alexhjames** [comment] 2022-10-03 19:33
@john-science I like the initial list. The "life cycle" of a reactor will need some careful thought. We will want to make sure that if you `loadState()` from different time nodes that you have consistent assembly numbering. That function appears to create a fresh reactor when you load a different time node but clearly the assembly probably should retain it's name/number between the two time nodes. 
 
https://github.com/terrapower/armi/blob/7725b8d5d306329e6bebb434a989a2097bf9d743/armi/bookkeeping/db/database3.py#L401

**Comment by john-science** [comment] 2022-10-03 20:36
> @john-science That's a great list! I especially dig the last bullet. Just a quick thought on the second bullet. We'll likely want to consider adds to the SFP as well. An example of this is here

Well, in 99% of the cases, assemblies are in a Reactor before they are in a SFP, so this problem solves itself.

In other cases, note that I said "using something like Core.add()".  So, other "SFP.add()" will also need the same tooling to add a name/ID to an assembly if it doesn't have one when it's added.

The SFP seems fine to me, at least for now.

**Comment by john-science** [comment] 2024-03-29 15:17
Assembly numbers are no longer global!

**Closed by john-science** 2024-03-29 15:17 UTC
Labels: architecture
