### ISSUE TITLE
Additional Testing for Axial Expansion Changer

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#847] opened 2022-08-22 23:06 UTC
Add two tests to axial expansion changer.

1. Verify volume fraction conservation
2. Verify that block masses are _not_ conserved. 
    - This can be checked simultaneously when the target component mass conservation is checked. 
    - There may be an opportunity to coalesce checks for i) block density conservation, ii) block mass non-conservation, iii) target component mass conservation. 
    - This should be done with thermal expansion on a single assembly for efficiency. 

_Originally posted by @jakehader / @mgjarrett in https://github.com/terrapower/armi/pull/845#issuecomment-1222821586 / https://github.com/terrapower/armi/pull/845#issuecomment-1222921652_

**Comment by jakehader** [comment] 2022-08-22 23:23
Duplicate of #848

**Closed by jakehader** 2022-08-22 23:23 UTC
Labels: testing
